# Generated by Django 5.0.2 on 2024-03-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('grupo', models.CharField(max_length=30)),
            ],
            options={
                'permissions': (('escuchar_cancion', 'escuchar cancion'), ('bajar_cancion', 'bajar cancion')),
            },
        ),
    ]
