# Generated by Django 4.2.3 on 2023-08-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_remove_book_pubdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-price']},
        ),
    ]
