# Generated by Django 4.2.4 on 2023-08-03 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VideoBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion13.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, null=True)),
                ('foto', models.ImageField(upload_to='images/')),
                ('videobook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion13.videobook')),
            ],
        ),
    ]
