# Generated by Django 5.0.2 on 2024-02-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='correo',
            field=models.EmailField(blank=True, max_length=80),
        ),
    ]
