# Generated by Django 5.0.2 on 2024-02-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_editor_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descuento',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
