# Generated by Django 5.0.2 on 2024-02-21 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_libro_autores'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroAutores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paginas', models.IntegerField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.autor')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.libro')),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(through='app.LibroAutores', to='app.autor'),
        ),
    ]
