# Generated by Django 5.0.2 on 2024-03-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_fotografia_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['price'], 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name_plural': 'Editores'},
        ),
        migrations.AddField(
            model_name='book',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
