# Generated by Django 4.2.3 on 2023-07-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='existencias',
        ),
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
